# Generated by Django 5.0.7 on 2024-09-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_student_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moreinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('about_me', models.TextField(blank=True)),
                ('can_post', models.BooleanField(default=False)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('year_of_graduation', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='can_post',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='student',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_graduation',
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
