# Generated by Django 5.0.7 on 2024-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_event_event_year_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accept_log',
            field=models.BooleanField(default=False),
        ),
    ]
