# Generated by Django 5.0.7 on 2024-10-07 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_student_accept_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Moreinfo',
        ),
        migrations.AddField(
            model_name='student',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nick_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
